//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMDO
    {
        public THAMDO()
        {
            this.CTTHAMDOes = new HashSet<CTTHAMDO>();
        }
    
        public int MaCH { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public string Noidungthamdo { get; set; }
        public Nullable<int> Tongsobinhchon { get; set; }
    
        public virtual ICollection<CTTHAMDO> CTTHAMDOes { get; set; }
    }
}
